# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    desc "Build Development"
    lane :buildDev do
        setup_ci if is_ci
        match(
            type: "development",
            app_identifier: "ch.thipok.method.dev",
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci,
        )
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method.dev",
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci,
        )
        increment_build_number()
        build_app(
            scheme: "dev",
            export_method: "app-store",
            output_directory: "./build/outputs/ipa/dev",
            export_options: {
                manageAppVersionAndBuildNumber: false
            },
        )
    end

    desc "Build Staging"
    lane :buildStg do
        setup_ci if is_ci
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method.stg",
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci
        )
        increment_build_number()
        build_app(
            scheme: "stg",
            export_method: "app-store",
            output_directory: "./build/outputs/ipa/stg",
            export_options: {
                manageAppVersionAndBuildNumber: false
            },
        )
    end

    desc "Build Production"
    lane :buildPrd do
        setup_ci if is_ci
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method",
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci
        )
        increment_build_number()
        build_app(
            scheme: "prd",
            export_method: "app-store",
            output_directory: "./build/outputs/ipa/prd",
            export_options: {
                manageAppVersionAndBuildNumber: false
            },
        )
    end

    desc "Deploy Development"
    lane :deployDev do
        app_store_connect_api_key(
            is_key_content_base64: true,
            in_house: false,
        )
        upload_to_testflight(
            ipa: "./build/outputs/ipa/dev/method.ipa",
            beta_app_feedback_email: "me@thipok.ch",
            beta_app_description: "Experiment with your thought.",
            demo_account_required: false,
            notify_external_testers: true,
            changelog: ENV["BUILD_TIME_HASH"],
        )
    end

    desc "Deploy Staging"
    lane :deployStg do
        app_store_connect_api_key(
            is_key_content_base64: true,
            in_house: false,
        )
        upload_to_testflight(
            ipa: "./build/outputs/ipa/stg/method.ipa",
            beta_app_feedback_email: "me@thipok.ch",
            beta_app_description: "Experiment with your thought.",
            demo_account_required: false,
            notify_external_testers: true,
            changelog: ENV["BUILD_TIME_HASH"],
        )
    end

    desc "Deploy Production"
    lane :deployPrd do
        app_store_connect_api_key(
            is_key_content_base64: true,
            in_house: false,
        )
        upload_to_app_store(
            ipa: "./build/outputs/ipa/prd/method.ipa",
            force: true,
        )
    end
end
