# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    desc "Build Development"
    lane :buildDev do
        setup_ci if is_ci
        match(
            type: "development",
            app_identifier: "ch.thipok.method.dev",
        )
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method.dev",
        )
        increment_build_number()
        build_app(
            scheme: "dev",
            export_method: "app-store",
            export_options: {
                manageAppVersionAndBuildNumber: false
            },
        )
    end

    desc "Build Staging"
    lane :buildStg do
        setup_ci if is_ci
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method.stg",
        )
        increment_build_number()
        build_app(
            export_method: "app-store",
            export_options: {
                manageAppVersionAndBuildNumber: false
            },
        )
    end

    desc "Build Production"
    lane :buildPrd do
        setup_ci if is_ci
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method",
        )
        increment_build_number()
        build_app(
            export_method: "app-store",
            export_options: {
                manageAppVersionAndBuildNumber: false
            },
        )
    end

    desc "Deploy Development"
    lane :deployDev do
        app_store_connect_api_key()
        upload_to_testflight()
    end

    desc "Deploy Staging"
    lane :deployStg do
        app_store_connect_api_key()
        upload_to_testflight()
    end

    desc "Deploy Production"
    lane :deployPrd do
        app_store_connect_api_key()
        upload_to_app_store()
    end
end
