# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

    desc "Build Development"
    lane :buildDev do
        setup_ci if ENV['CI']
        match(
            type: "development",
            app_identifier: "ch.thipok.method.dev",
            git_url: ENV["MATCH_GIT_REPO"],
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci,
        )
        increment_build_number(
          build_number: ENV["BUILD_TIME_HASH"],
        )
        build_app(
            scheme: "dev",
            export_method: "development",
            output_directory: "./build/outputs/ipa/dev",
        )
    end

    desc "Build Staging"
    lane :buildStg do
        setup_ci if ENV['CI']
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method.stg",
            git_url: ENV["MATCH_GIT_REPO"],
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci
        )
        increment_build_number(
          build_number: ENV["BUILD_TIME_HASH"],
        )
        build_app(
            scheme: "stg",
            export_method: "app-store",
            output_directory: "./build/outputs/ipa/stg",
        )
    end

    desc "Build Preview"
    lane :buildPrd do
        setup_ci if ENV['CI']
        match(
            type: "appstore",
            app_identifier: "ch.thipok.method",
            git_url: ENV["MATCH_GIT_REPO"],
            # MATCH_PASSWORD env for match password
            storage_mode: "git",
            readonly: is_ci
        )
        increment_build_number(
          build_number: ENV["BUILD_TIME_HASH"],
        )
        build_app(
            scheme: "prd",
            export_method: "app-store",
            output_directory: "./build/outputs/ipa/prd",
        )
    end
end
