name: Develop Pipeline

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  build-darwin:
    name: Gradle Build + Analysis Darwin
    runs-on: macos-latest
    #    if: ${{ !startsWith(github.event.head_commit.message, 'wip') }}
    steps:
      - name: Checking out repo.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Deep Fetch

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Setup ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.0' # Not needed with a .ruby-version file
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          working-directory: ${{ github.workspace }}/darwin

      - name: Setup sonarqube
        uses: warchant/setup-sonar-scanner@v3

      - name: Setting up Gradle.
        uses: ./.github/actions/setup

      - name: Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SECRETS_PASSWORD: ${{ secrets.SECRETS_PASSWORD }}
          SECRETS_REPO: ${{ secrets.SECRETS_REPO }}
          GRGIT_USER: ${{ secrets.GRGIT_USER }}
        run: ./gradlew assembleDev check sonarqube --scan --info --stacktrace

      - name: Upload IPA
        uses: actions/upload-artifact@master
        with:
          name: darwin-ipa
          path: darwin/build/outputs/ipa

      - name: Upload APK
        uses: actions/upload-artifact@master
        with:
          name: android-apk
          path: android/build/outputs/apk

      - name: Upload logs
        if: ${{ always() }}
        uses: actions/upload-artifact@master
        with:
          name: logs
          path: |
            ~/Library/Logs/gym
