name: Develop Pipeline

on:
  push:
    branches:
      - dev

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

  # BUILD + CHECK

  build:
    name: Gradle Build + Check
    runs-on: macos-latest
    #    if: ${{ !startsWith(github.event.head_commit.message, 'wip') }}
    steps:
      - name: Checking out repo.
        uses: actions/checkout@v3
        with:
          fetch-depth: 0  # Deep Fetch

      - name: Setting up Gradle.
        uses: ./.github/actions/setup

      - name: Cache SonarCloud packages
        uses: actions/cache@v1
        with:
          path: ~/.sonar/cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Gradle build
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}  # Needed to get PR information, if any
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}

          FIREBASE_APPID_IOS_DEV: ${{ secrets.FIREBASE_APPID_IOS_DEV }}
          FIREBASE_APPID_IOS_PRE: ${{ secrets.FIREBASE_APPID_IOS_PRE }}
          FIREBASE_APPID_IOS_PRD: ${{ secrets.FIREBASE_APPID_IOS_PRD }}

          FIREBASE_APPID_ANDROID_DEV: ${{ secrets.FIREBASE_APPID_ANDROID_DEV }}
          FIREBASE_APPID_ANDROID_PRE: ${{ secrets.FIREBASE_APPID_ANDROID_PRE }}
          FIREBASE_APPID_ANDROID_PRD: ${{ secrets.FIREBASE_APPID_ANDROID_PRD }}

          FIREBASE_APPID_WEB_DEV: ${{ secrets.FIREBASE_APPID_WEB_DEV }}
          FIREBASE_APPID_WEB_PRE: ${{ secrets.FIREBASE_APPID_WEB_PRE }}
          FIREBASE_APPID_WEB_PRD: ${{ secrets.FIREBASE_APPID_WEB_PRD }}
        run: ./gradlew build sonarqube --info